version: '{build}'
branches:
  only:
  - master  
skip_tags: true
image: Visual Studio 2019
configuration: Release
platform: x86
nuget:
  project_feed: true
before_build:
- cmd: >-
   
    git submodule update --init --recursive

    nuget restore
build:
  project: SADXModManager.sln  
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal  
artifacts:
- path: C:\projects\sadx-manager-classic\bin\SADXModManager.exe
  name: sadxmodmanager

before_deploy:
- ps: |-
      if (!$env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED) {
        $env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED = "$env:APPVEYOR_REPO_COMMIT_MESSAGE"
      }

deploy:
- provider: GitHub
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED)
  auth_token:
    secure: 3U0hYOvkeEJsoN2b4U/c9UpG+OoVIqNa7EtW9r2+FbdvP7m2ul7i1oCKz+gUyx+khXCfbKrOSvSWzk8nYTAme9yv/ZCUchsuuCF8vltt5XT2faWG/TsDq9+KxiW9o3cb
  artifact: sadxmodmanager
  on:
    branch: master